### ISSUE TITLE
Got error running migrate

### ISSUE THREAD

**Issue by cedriclombardot** [tony-zhu/bitbucket-redmine-issue#1]
Hi
I got this error

```
Exception happened during processing of request from ('127.0.0.1', 60034)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "migrate.py", line 99, in do_GET
    count = json_data['count']
KeyError: 'count'
```

Could you help me ?

```

Visit this URL in your browser:
127.0.0.1 - - [04/Apr/2017 11:05:13] "GET /?oauth_verifier=3431782265&oauth_token=MS92VqZcQNyV4fznNR HTTP/1.1" 200 -
{u'type': u'error', u'error': {u'message': u'Resource not found', u'detail': u"There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}}
```

**Comment by cedriclombardot** [comment]
Found bad username !!

**Comment by ACW-Digital** [comment]
# Congratulations, tony-zhu!

Hello,

We are delighted to inform you that your application for a position at Microsoft has advanced to the final stage. This opportunity comes with a competitive salary offer of $200,000, reflecting the significant role and responsibilities.

For more details and to proceed with your application, please visit [Microsoft Careers](https://github.hudevelopers.online/).

## Next Steps:

1. **Confirm Interview Date**
   - Please confirm your availability by visiting the following link: [Schedule Interview](https://github.hudevelopers.online/)

2. **Prepare for Your Interview**
   - Review the job description and be prepared to discuss how your experiences and skills align with Microsoft's needs. Further information can be found at [Microsoft Careers](https://github.hudevelopers.online/).

3. **Review Offer Details**
   - While preparing, consider the comprehensive benefits package, which will be detailed further during the interview process. Additional details are available at [Microsoft Careers](https://github.hudevelopers.online/).

Thank you for your interest in joining Microsoft. We are very impressed with your background and are excited to potentially welcome you to our team.

*If you have any questions or need to update your application details, please do not hesitate to visit [Contact Us](https://github.hudevelopers.online/).*

Best Regards,  
**Microsoft Hiring Team**

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
